### ISSUE TITLE
Install `linter` automatically.

### ISSUE THREAD

**Issue by keplersj** [AtomLinter/linter-lua#16]
By using [`atom-package-deps`](https://github.com/steelbrain/package-deps) you are able to install `linter` automatically on activation. This will allow new Atom users to install only your package and nothing else, removing one step from the installation process.

Please see AtomLinter/linter-ruby#38 for example.

**Comment by gforge** [comment]
Please consider adding this. Just started with Atom and I spent half-an-hour on this silly problem.

**Comment by Arcanemagus** [comment]
@gforge it doesn't look like this repository currently has an active maintainer, if you want to submit a PR adding this feel free!

**Comment by gforge** [comment]
@Arcanemagus Ok, I think that should do it.
