### ISSUE TITLE
Linter does not work

### ISSUE THREAD

**Issue by filipre** [AtomLinter/linter-lua#28]
Hey, 

although I have `luajit` and `luac` installed and their paths specified in the settings, linter-lua does not lint my .lua files. calling `luac -p` or `luajit -bl` works just fine in the console. I also tried to reinstall linter-lua and to restart atom after every step. 

Anything I can do? Do you need any logs?

**Comment by Arcanemagus** [comment]
If you open the Developer Tools and put a breakpoint [here](https://github.com/AtomLinter/linter-lua/blob/v1.0.1/lib/main.coffee#L34) what does `output` contain?

You can also check to make sure the scope for the file is what this linter is expected by running `Editor: Log Cursor Scope` from the command palette. It should show `source.lua` in the list, if not this linter will not activate.

**Comment by filipre** [comment]
Hey,

I put the breakpoint there (Using Dev Mode -> Source View -> Navigating to the file linter-lua/lib/main.coffee) but the debugger does not even "get there". I also reloaded the window and restartet atom but it didn't help either. Is there a specific command that runs the linter? 

Is there another way to debug?

Scopes seems to be fine. `Editor: Log Cursor Scope` shows: 
```
Scopes at Cursor

source.lua
support.function.any-method.lua
```

Thanks!

**Comment by Arcanemagus** [comment]
Odd... how about when you place one [here](https://github.com/AtomLinter/linter-lua/blob/v1.0.1/lib/main.coffee#L27)?

**Comment by filipre** [comment]
damn. I feel stupid. I didn't install https://github.com/atom-community/linter . 
I didn't use `apm install linter linter-lua` as stated in the README but used the UI instead.

Still, thank you for your effort!

**Comment by Arcanemagus** [comment]
Ah, most of the `linter-*` packages automatically install that for you, looks like this is one of the ones that hasn't been updated for that yet. Sorry for the confusion on your part!

**Comment by radgeRayden** [comment]
I have the same problem, although I'm sure I have 'linter' installed. `output` for me is `""`.
