### ISSUE TITLE
spawn luac ENOENT although I have installed luajit

### ISSUE THREAD

**Issue by santisy** [AtomLinter/linter-lua#34]
I installed torch and luajit is in it. But it seemed that `linter-lua` could not find it, and showed error `spawn luac ENOENT`.

I have added the path to init.coffee and also have , but still `linter-lua` just cannot use lua-jit.

**Comment by Arcanemagus** [comment]
What OS are you on?

**Comment by santisy** [comment]
@Arcanemagus Thanks for reply, I am using Ubuntu Linux 14.04 LTS

**Comment by Arcanemagus** [comment]
Hmmm, if you put the output of `where luac` into the Executable Path setting, does it work for you then?

**Comment by santisy** [comment]
@Arcanemagus `where luac` shows nothing..... I only have luajit with my torch

**Comment by Arcanemagus** [comment]
Ah, looks like from the description of that option `luajit` should work just as well, so put the output of `where luajit` in the Executable Path setting.

**Comment by santisy** [comment]
@Arcanemagus Do you mean `which luajit` ? I have added the path but still not working. sad ....

**Comment by Arcanemagus** [comment]
It's giving you `ENOENT` even when you specify the full path? Is it showing that full path in the error message?

**Comment by Ombridride** [comment]
Hi,

Same issue in my side with a Debian Jessie 8.4 up to date
![](http://i.imgur.com/JhAZaCJ.png)
![](http://i.imgur.com/JhAZaCJ.png)

![](http://i.imgur.com/WKofHGU.png)
![](http://i.imgur.com/268Yrll.png)

luac not installed, luajit installed with path :
![](http://i.imgur.com/NJEQbXP.png)

**Comment by Arcanemagus** [comment]
@Ombridride Although this package can _use_ the output of `luajit`, by default it is only configured to use `luac`. If you specify the path to `luajit` in the settings as the Executable Path does it work then?

**Comment by Ombridride** [comment]
Didn't see it !
I added luajit on the setting path :
![](http://i.imgur.com/EJ4O4rg.png)

Then tried to do an error on a LUA file :
![](http://i.imgur.com/vJTy4WF.png)
It works great, thank you :)
I think it was the same issue as @santisy and you can close this issue

(PS : luajit in default setting seems better in my point of view)

**Comment by Arcanemagus** [comment]
@santisy said it wasn't working for them [here](https://github.com/AtomLinter/linter-lua/issues/34#issuecomment-216026379), so I'll leave this open for a while longer before marking it as closed due to lack of response :stuck_out_tongue:.
