### ISSUE TITLE
How to configure path to Luac executable?

### ISSUE THREAD

**Issue by Zireael07** [AtomLinter/linter-lua#5]
See issue title.

I can't get the linter to work even though I have Lua 5.3.2 on my system.

**Comment by xpol** [comment]
#6 add this config settings. Just wait next release.

**Comment by Zireael07** [comment]
Thanks.
In my case, it turns out I had extraneous spaces in my PATH environment variable, so it works now :)

**Comment by hd-deman** [comment]
executable path settings available since 0.1.5 release
