### ISSUE TITLE
Linter not running

### ISSUE THREAD

**Issue by discon-nected** [AtomLinter/linter-lua#82]
Can't seem to get linter-lua working.
Installed using `apm install linter linter-lua`
No linting happening. Here are my details...
OS: Ubuntu 20.04
```
$ luajit -v
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
```
```
$ atom -v
Atom    : 1.47.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
```
```
$ which luajit
/usr/bin/luajit
```
![image](https://user-images.githubusercontent.com/20234985/84620338-d4fc9900-af2b-11ea-8a50-d082052443ed.png)

**Comment by vzamanillo** [comment]
Hey! try installing `language-lua`

`apm install language-lua`

**Comment by vzamanillo** [comment]
Updated README #83

**Comment by discon-nected** [comment]
That solved it. Thanks!
